Update "insights-client not connected" Data Collector filter value
RedHatInsights/insights-inventory-frontend pull request #1563
Opened 2022-05-17 16:09 UTC by kruai

Addresses [ESSNTL-2805](https://issues.redhat.com/browse/ESSNTL-2805) and [ESSNTL-2705](https://issues.redhat.com/browse/ESSNTL-2705). 

Selecting "insights-client not connected" in the Data Collector filter currently adds a System Profile filter to the API request. That ended up causing issues when combined with the `registered_with` filter, so we've added some new functionality to the back-end.
With the changes in this PR, it will instead send `&registered_with=!puptoo`, which means "only return hosts that have _not_ been reported by puptoo within the standard culling period"; it does exactly the opposite of `&registered_with=puptoo`.
Note that you can do this for other data collectors/reporters, e.g. `!yupana` and `!rhsm-conduit`.

This is dependent on the HBI API's [PR 1130](https://github.com/RedHatInsights/insights-host-inventory/pull/1130), which delivers the above `!` functionality.

2022-05-19 10:56 UTC, MichalSajdik requested changes

2022-05-19 13:17 UTC, kruai commented on src/api/api.js
>          const insightsConnectedFilter = filters?.registeredWithFilter?.filter(filter => filter !== 'nil');
Done! Removed that const entirely since the extra processing is no longer necessary

2022-05-19 13:17 UTC, kruai commented on src/api/api.js
>      const insightsConnectedFilter = registeredWithFilter?.filter(filter => filter !== 'nil');
Done! Removed that const entirely since the extra processing is no longer necessary

2022-05-19 13:29 UTC, kruai commented
@MichalSajdik I made the changes you requested

2022-05-24 07:57 UTC, MichalSajdik approved these changes

2022-05-31 14:00 UTC, merged