fix(ESSNTL-3378): make all apps consistent to handle insights-not-connected
RedHatInsights/insights-inventory-frontend pull request #1703
Opened 2022-11-15 13:51 UTC by mkholjuraev

Resolves: https://issues.redhat.com/browse/ESSNTL-3378

To test:

1. Visit the inventory page
2. filter the table with 'insights-not-connected' from the Data-collector filter
3. Click on a system to open the details page
4. Observe that all tabs are consistent and display the following design.

![image](https://user-images.githubusercontent.com/59481011/201936196-98b2b1d4-1a1c-4fb9-ab0c-911ad7d44116.png)

2022-11-16 13:14 UTC, gkarat commented
Didn't work for me: the message is not updated after navigating to any of the tabs.

[Screencast from 11-16-2022 02:12:29 PM.webm](https://user-images.githubusercontent.com/31385370/202189951-526d8ef4-6785-4019-a890-a5b216d33969.webm)

2022-11-16 13:16 UTC, gkarat requested changes

2022-11-16 13:16 UTC, gkarat commented on src/components/InventoryDetail/__snapshots__/AppInfo.test.js.snap
> +exports[`AppInfo should render correctly 1`] = `ReactWrapper {}`;
I am afraid the snapshot is not correct: it's just an empty object. Did you mount the component the right way?

2022-11-16 20:29 UTC, mkholjuraev commented
The UX behavior might change due. Putting this ticket on hold.

2023-04-26 08:19 UTC, mkholjuraev commented
Closing this as the ticket is resolved on another duplicated one.

2023-04-26 08:19 UTC, closed without merging