chore: upgrade react-router
RedHatInsights/insights-inventory-frontend pull request #1968
Opened 2023-08-10 12:23 UTC by mkholjuraev

Resolves: https://issues.redhat.com/browse/ESSNTL-4076

Upgrades react-router to v6 and refactors all class components to function components

2023-08-11 12:18 UTC, gkarat requested changes

2023-08-11 12:18 UTC, gkarat commented on src/components/InventoryTable/EntityTable.js
> +    navigate(
I think here we can freely use `navigate` from react-router and just replace with `navigate(key)` (using relative path).

2023-08-11 12:18 UTC, gkarat commented on src/components/InventoryDetail/helpers.js
> +      console.log('hello');
```suggestion
```

2023-08-11 12:18 UTC, gkarat commented on src/Utilities/TestingUtilities.js
> +    <MemoryRouter initialEntriest={initialEntriest}>{Component}</MemoryRouter>
```suggestion
    <MemoryRouter initialEntries={initialEntries}>{Component}</MemoryRouter>
```

2023-08-11 12:18 UTC, gkarat commented on src/Utilities/TestingUtilities.js
> +export const mountWithRouter = (Component, initialEntriest) => {
```suggestion
export const mountWithRouter = (Component, initialEntries) => {
```

2023-08-11 12:27 UTC, gkarat commented on src/Routes.js
> +  let element = useRoutes([
I think we miss redirect here: see the old `<Redirect path="*" to="/" />`

2023-08-16 08:11 UTC, mkholjuraev commented
@gkarat why there is a rage label?

2023-08-16 08:19 UTC, gkarat commented
Haha, it just reflects my feelings working on the router upgrade 😄

2023-08-17 09:49 UTC, gkarat approved these changes
LGTM! The last issue was resolved, and I can see the app working fine locally. Let's push it next 🚀

2023-08-17 15:22 UTC, merged

2023-08-21 10:26 UTC, gkarat commented
:tada: This PR is included in version 1.37.0 :tada:

The release is available on [GitHub release](https://github.com/RedHatInsights/insights-inventory-frontend/releases/tag/v1.37.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: