fix(ESSNTL-5612): Update Staleness & Deletion Keys + Route Protection
RedHatInsights/insights-inventory-frontend pull request #2114
Opened 2023-12-04 21:42 UTC by adonispuente

There should be no functionality changes frontend wise with this PR. The backend is changing the api keys so the frontend needs to be updated. 

This also protects the route via feature flag.
This cannot be merged until https://github.com/RedHatInsights/insights-host-inventory/pull/1573 is merged 

New keys with merged PR: 
conventional_time_to_stale
"conventional_time_to_stale_warning": "",
        "conventional_time_to_delete": "",
        "immutable_time_to_stale": "",
        "immutable_time_to_stale_warning": "",
        "immutable_time_to_delete"

2023-12-11 12:56 UTC, mkholjuraev commented
/retest

2023-12-11 13:05 UTC, mkholjuraev requested changes
While testing locally, I encountered this error:

`{
    "detail": "Validation Error: {'conventional_time_to_deletion': ['Unknown field.']}",
    "status": 400,
    "title": "Bad Request",
    "type": "about:blank"
}`

2023-12-11 14:27 UTC, adonispuente commented
@mkholjuraev Sorry about that, The ticket wasnt up to date and I was using an old schema, Ive updated the PR so that its uses the api keys that are now merged into BE stage

2023-12-11 14:46 UTC, adonispuente commented
/retest

2023-12-11 14:53 UTC, mkholjuraev approved these changes
LGTM! everyting works as described. Let's make the commit lint happy and then merge

2023-12-11 20:42 UTC, adonispuente commented
/retest

2023-12-12 13:10 UTC, adonispuente commented
/retest

2023-12-13 10:22 UTC, gkarat commented
/retest

2023-12-13 10:51 UTC, computercamplove commented
/retest

2023-12-13 13:07 UTC, merged

2023-12-13 13:35 UTC, gkarat commented
:tada: This PR is included in version 1.61.3 :tada:

The release is available on [GitHub release](https://github.com/RedHatInsights/insights-inventory-frontend/releases/tag/v1.61.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: