temp
RedHatInsights/insights-inventory-frontend pull request #2130
Opened 2023-12-22 00:02 UTC by LiorKGOW

2024-01-09 17:30 UTC, LiorKGOW commented
Thank you @gkarat for helping me with this PR ! 
It is now ready for review ✌🏼

2024-01-09 20:39 UTC, gkarat requested changes
Everything looks good to me! However, I believe we better no to touch `value` for the IPv4, IPv6, and Interfaces/NICs fields. The problem is that if any of the arrays for this fields is empty, they will render "Not available addresses" text which is not correct. It must show "0 addresses" IIRC.

<img width="438" alt="image" src="https://github.com/RedHatInsights/insights-inventory-frontend/assets/31385370/b97c10d8-33d2-4e6e-a693-dd9f7240fcb4">

So let's just focus on the newly added fields (DNS, Public IP) and, if would be necessary in the future change the value logic for other fields in a separate PR.

2024-01-11 08:53 UTC, LiorKGOW commented
Thank you for the review @gkarat !  

I have removed the second commit like you requested 
The PR is now ready for another review 👍🏼

2024-01-11 12:54 UTC, gkarat approved these changes
LGTM! Thank you @LiorKGOW

2024-01-11 12:55 UTC, merged

2024-01-11 13:16 UTC, gkarat commented
:tada: This PR is included in version 1.64.0 :tada:

The release is available on [GitHub release](https://github.com/RedHatInsights/insights-inventory-frontend/releases/tag/v1.64.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: